import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { getFirebase } from "../firebase";
import Enduro from "../timekeeping/enduro";
import { toJSON } from "../timekeeping/serializeJSON";
import { fromRS } from "../timekeeping/serializeRS";
import { RouteSheetViewer } from "./routesheetView";

$('#import').on('click', async function () {
  const rsFile = $('#rs')?.val()?.toString().trim() ?? ''
  if (rsFile.length === 0) {
    alert('Invalid RS File')
    return
  }
  const enduro: Enduro = fromRS(rsFile)
  if (!enduro) {
    alert('Invalid RS File')
    return
  }
  const json = toJSON(enduro)

  try {
    const db = getFirebase().firestore
    const docRef = await addDoc(collection(db, "enduros"), {
      //id: will be auto-generated by Firestore
      userId: getFirebase().auth.currentUser?.uid,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
      isPublished: false,
      ...json
    });
    console.log(`Created new enduro ${docRef.id}`)
    window.location.href = `/enduroEdit.html?id=${docRef.id}`
  } catch (e) {
    console.error('Failed to create new enduro')
    console.error(e)
    alert('Error Saving Enduro: ' + e);
  }
});

$('#rs').on('input change propertychange', (_e) => {
  showPreview($('#rs').val())
})

$('#choose').on('click', () => {
  $('#import_page input[type="file"]')[0].click()
})

$('#import_page input[type="file"]').on('change', (e) => {
  const target = (e.target as HTMLInputElement)
  if (!target || target.files?.length === 0) {
    return
  }
  const file = target.files![0]
  const reader = new FileReader();

  reader.readAsText(file);

  reader.onload = function() {
    if (reader.result) {
      const rsFile = reader.result.toString()
      $('#rs').val(reader.result.toString())
      showPreview(rsFile)
    } else {
      console.warn('Import of RS file found no content.')
    }
  };
})

function showPreview(rsFile) {
  $('#preview').show()
  rsFile = rsFile.trim();
  $('#routeSheet').empty()
  try {
    const enduro: Enduro = fromRS(rsFile);
    new RouteSheetViewer(enduro.routeSheet, $('#routeSheet'));
  } catch (e) {
    $('#routeSheet').append('Invalid RS File')
    console.log(e)
  }
}